# Load Rucola tasks
SOURCE_ROOT = File.dirname(__FILE__)
require 'rubygems'
require 'rucola/rucola_support'
load 'rucola/tasks/main.rake'

# Application configuration

# You only need to specify this if for some reason the applications name
# might be different than the one specified in the Info.plist file under key: CFBundleExecutable
#
# APPNAME = "CampfireTest"
# TARGET  = "#{APPNAME}.app"

# You only need to specify this if for some reason the applications version
# might be different than the one specified in the Info.plist file under key: CFBundleVersion
#
# APPVERSION = INFO_PLIST['CFBundleShortVersionString']
# APPVERSION = "rev#{`svn info`[/Revision: (\d+)/, 1]}"
# APPVERSION = Time.now.strftime("%Y-%m-%d")

# PUBLISH_URI = URI.parse('scp://yourname@yourhost:port/path')
# APPCAST_URI = PUBLISH_URI

# Tasks

desc 'Deploy a release build.'
task :deploy do
  puts "\nDeploying...\n\n"
  
  Rake::Task['release'].invoke
  Rake::Task['deploy:package'].invoke
  # Rake::Task['deploy:sparkle_appcast'].invoke
  # Rake::Task['deploy:release_notes'].invoke
  # Rake::Task['deploy:upload'].invoke
  # Rake::Task['xcode:clean'].invoke
  Rake::Task['dependencies:clean'].invoke
end

namespace :deploy do
  desc 'Prepare a package to be used as a webapp base app'
  task :package_webapp_base_app => ['dependencies:copy', :release, :pkg] do
    sh "cd build/Release && /usr/bin/tar -cjf ../../pkg/webapp_base_app.tar.bz2 CampfireTest.app"
  end
end