# Load Rucola tasks
SOURCE_ROOT = File.dirname(__FILE__)
require 'rubygems'
require 'rucola/rucola_support'
load 'rucola/tasks/main.rake'

# Application configuration

# You only need to specify this if for some reason the applications name
# might be different than the one specified in the Info.plist file under key: CFBundleExecutable
#
# APPNAME = "WebApp"
# TARGET  = "#{APPNAME}.app"

# You only need to specify this if for some reason the applications version
# might be different than the one specified in the Info.plist file under key: CFBundleVersion
#
# APPVERSION = INFO_PLIST['CFBundleShortVersionString']
# APPVERSION = "rev#{`svn info`[/Revision: (\d+)/, 1]}"
# APPVERSION = Time.now.strftime("%Y-%m-%d")

# Use these constants to define the urls that should be used by the deploy:upload task.
#
# PUBLISH_URI = URI.parse('scp://yourname@yourhost:port/path')
# APPCAST_URI = PUBLISH_URI

# Tasks

desc 'Deploy a release build.'
task :deploy do
  puts "\nDeploying...\n\n"
  
  sh "cd ../WebAppApplication && rake deploy:package_webapp_base_app"
  sh "cp ../WebAppApplication/pkg/webapp_base_app.tar.bz2 app/assets/"
  
  Rake::Task['release'].invoke
  Rake::Task['deploy:package'].invoke
  # Rake::Task['deploy:sparkle_appcast'].invoke
  # Rake::Task['deploy:release_notes'].invoke
  # Rake::Task['deploy:upload'].invoke
  Rake::Task['xcode:clean'].invoke
  Rake::Task['dependencies:clean'].invoke
end

desc 'Clean WebApp and WebAppApplication'
task :clean_all => :clean do
  sh "cd ../WebAppApplication && rake clean"
end